from gooey import Gooey, GooeyParser
@Gooey(program_name="Tamrin 5",
       program_description = "To Store ID",
       default_size=(700, 600))
def main():
    parser = GooeyParser()
    parser.add_argument("Name_1", help="PLZ Enter Your Name")
    parser.add_argument("Last_Name_1", help="PLZ Enter Your Last Name")
    parser.add_argument("ID_1", help="PLZ Enter ID Number")
    parser.add_argument("Name_2", help="PLZ Enter Your Name")
    parser.add_argument("Last_Name_2", help="PLZ Enter Your Last Name")
    parser.add_argument("ID_2", help="PLZ Enter ID Number")
    parser.add_argument("Name_3", help="PLZ Enter Your Name")
    parser.add_argument("Last_Name_3", help="PLZ Enter Your Last Name")
    parser.add_argument("ID_3", help="PLZ Enter ID Number")
    args = parser.parse_args()
    with open("database5.txt", "w") as f:
        f.write(args.Name_1)
        f.write(" ")
        f.write(args.Last_Name_1)
        f.write(" ")
        f.write(args.ID_1)
        f.write("\n")
        f.write(args.Name_2)
        f.write(" ")
        f.write(args.Last_Name_2)
        f.write(" ")
        f.write(args.ID_2)
        f.write("\n")
        f.write(args.Name_3)
        f.write(" ")
        f.write(args.Last_Name_3)
        f.write(" ")
        f.write(args.ID_3)
main()
